<br/>
<h1>Modifier un produit</h1>

<form id="form1" method="post">
		<table>
			<tr>
			<td>id produit : </td>
			<td>
				<input type="text" id="id" name="id" readonly="true"
				value="<?php echo $this->viewData['produit']->getidProducts();?>"/>
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("idProducts");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Type de produit : </td>
			<td>
				<input type="text" id="type_produit_HEF" name="type_produit_HEF"
				 value="<?php echo $this->viewData['produit']->gettype_produit_HEF();?>"/>
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("type_produit_HEF");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Prix  : </td>
			<td>
				<input type="text" id="prix" name="prix" value="<?php echo $this->viewData['produit']->getPrix();?>"/>(DH)
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("prix");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Déscription : </td>
			<td><textarea type="text" id="description" name="description" rows="3" cols="17"> 
				 <?php echo $this->viewData['produit']->getdescription();?></TEXTAREA>
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("description");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>petite Déscription : </td>
			<td><input type="text"  name="small_description" value="<?php echo $this->viewData['produit']->getsmall_description();?>"/>
				<span id="erreur">
				<?php 
				echo $this->viewData['produit']->ValidationMessage("small_description");
				?></span>
			</td>
		</tr>
		<tr>
			<td>Quantité : </td>
			<td><input type="text" id="quantite" name="quantite" value="<?php echo $this->viewData['produit']->getQuantite();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData['produit']->ValidationMessage("quantite");
			?></span>
		</td>
		</tr>
		<tr>
			<td>Date de MAJ : </td>
			<td><input type="text" id="date_de_maj" name="date_de_maj" readonly="true"value="<?php echo $this->viewData['produit']->getdate_de_maj();?>"/>
				<input type="date" id="date" name="date_de_maj" value="<?php echo $this->viewData['produit']->getdate_de_maj();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData['produit']->ValidationMessage("date");
			?></span></td>
		</tr>
		<tr>
			<td>Numéro Catégorie : </td>
			<td>
			<select id="Categories_idCategory" name="Categories_idCategory">
				<option><?php 	
					
								echo $this->viewData['produit']->getCategories_idCategory();
								
						
				?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td>image : </td>
			<td><input type="file" value="<?php echo $this->viewData['produit']->getimage();?>" name="image" class="btn"/></td>
		</tr>
		</tr>
		<tr><td colspan='2'><input type="submit" value= "Modifier" class="btn"/></td></tr>
	</table>
</form>