<br/>
<h1>Supprimer un produit</h1>

<form id="form1" method="post">
		<table>
			<tr>
			<td>id produit : </td>
			<td>
				<input type="text" id="id" name="id" readonly="true"
				value="<?php echo $this->viewData['produit']->getidProducts();?>"/>
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("getidProducts");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Type de produit : </td>
			<td>
				<input type="text" id="gettype_produit_HEF" name="gettype_produit_HEF"  readonly="true"
				value="<?php echo $this->viewData['produit']->gettype_produit_HEF();?>"/>
				<span id="erreur">
					<?php 
						echo $this->viewData['produit']->ValidationMessage("gettype_produit_HEF");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Prix Unitaire : </td>
			<td>
				<input type="text" id="prix" name="prix" 
				value="<?php echo $this->viewData['produit']->getPrix();?>" readonly="true"/>(DH)
				<span id="erreur">
					<?php 
					echo $this->viewData['produit']->ValidationMessage("prixUnitaire");
					?>
				</span>
			</td>
		</tr>
		<tr>
			<td>Déscription : </td>
			<td>
				<textarea type="text" id="description" name="description" rows="3" cols="17" readonly="true"> 
				 <?php echo $this->viewData['produit']->getdescription();?></TEXTAREA>
				<span id="erreur">
				<?php 
				echo $this->viewData['produit']->ValidationMessage("tva");
				?></span>
			</td>
		</tr>
		<tr>
			<td>petite Déscription : </td>
			<td>
				<input  id="s_desc" name="s_desc" readonly="true" value="
					<?php echo $this->viewData['produit']->getsmall_description();?>"
				/>
				<span id="erreur">
				<?php 
				echo $this->viewData['produit']->ValidationMessage("small_description");
				?></span>
			</td>
		</tr>
		<tr>
			<td>Quantité : </td>
			<td><input type="text" id="quantite" name="quantite" readonly="true"
			value="<?php echo $this->viewData['produit']->getQuantite();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData['produit']->ValidationMessage("quantite");
			?></span>
		</td>
		</tr>
		<tr>
			<td>Date de MAJ : </td>
			<td><input type="text" id="date" name="date" readonly="true"
			value="<?php echo $this->viewData['produit']->getdate_de_maj();?>"/>
			<span id="erreur">
			<?php 
			echo $this->viewData['produit']->ValidationMessage("date");
			?></span></td>
		</tr>
		<tr>
			<td>Numéro Catégorie : </td>
			<td>
			<select id="" readonly="true">
				<option><?php echo $this->viewData['produit']->getCategories_idCategory();?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td>image : </td>
			<td><input readonly="true" type="text" value="<?php echo $this->viewData['produit']->getimage();?>" class="btn"/></td>
		</tr>
		<tr><td colspan='2'><input type="submit" value= "Supprimer" class="btn"/></td></tr>
	</table>
</form>
<a href="?controler=Produit" class="link">Retour</a>